name: Desplegando pagina estatica en S3
on:
#  push:
#    branches:
#      - main  # Change to your default branch

  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Target ENV i.e: qa, dev, prod'     
        required: true
        default: 'qa'   

jobs:
 deploy:
   runs-on: ubuntu-latest


   steps:
     - name: Checkout repository
       uses: actions/checkout@v4


     - name: Set up AWS CLI ‚öôÔ∏è
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1


     - name: Deploy to AWS S3 üòÄ
       run: |
         aws s3 sync . s3://raynerprojectv2.click --delete

 